### ISSUE TITLE
Problems about this Patch

### ISSUE THREAD

**Issue by yangeos** [ManlyMarco/AI-HF_Patch#5]
1. Can't properly load character cards and mods
    (1) when load the character mod (installed by this patch) from the 'Face Tab',  eyes/lips/etc. don't show at the correct position, some characters don't change the shape of head. so they really look like ghosts (joke) ...
   (2) the same situation happen when load the 3-rd party character cards from ' the last top tab'.  If load the cards created by the original steam game (even with the official EcstasyPatch0501) this problem doesn't happen.

2. Can't properly display Chinese language, words appear in some squares look like the Font missing problem in Linux, but the game is running  in windows 10  :-)
For now, the Steam released the game version with Chinese support, but version is still 1.0.1.  Does this change leads to this problem and problem 1  ？？？？？

3. When I‘m trying to assemble my minimal set of plugins as you offered in this patch（because I only need sideloader and uncensore plugins），some problems happen：
（1） in character maker，mods never show。
（2） uncensore selector drop down list nerver show and no effect on the character when making，but the AI_overlay_mod plugin shows  and  in-game the character is uncensored.  That is Strange :-(
Because you are the creator of main plugins so I post this question here，hope you can do me a favor  :-）

All I  used  are    BepinEX 5.0.1 the latest stable release
                           IllusionFixes_AIGirl_13.1
                           XUnity.ResourceRedirector-BepIn-5x-1.1.2
                           BepInEx.MessageCenter_v1.1
                           BepInEx.ConfigurationManager_v15.1
                           AI_BepisPlugins_r15.1
                           AIAPI_1.12.1
                           AI_OverlayMods_5.2
                           AI_UncensorSelector v3.9

**Comment by ManlyMarco** [comment]
I replied to your comment on patreon. To summarize:
1 - Install the patch with all default settings and at the end tell it to look for mod updates. You can wait for the next version of hf patch to get all updates easily.
2 - The Chinese font issue is known and will be fixed in the next version.
3 - Modding the steam release manually is not trivial, you need to install at least illusionfixes by following instructions in its readme (if installing hf patch make sure illusionfixes are enabled). Anything more you should ask in the help channel of the discord server since it's not an issue with the patch.

**Comment by ManlyMarco** [comment]
The Chinese font issue should be fixed in the latest release. You need to apply any pending Steam updates before installing the patch.
